-- INSERTAR REGISTRO EN LA TABLA TICKETS

INSERT INTO TICKETS (IDOPERARIO, IDTURNO, IDCLIENTE, IDEMPRESA, IDPRODUCTO, FECHA, ORIGEN, DESTINO, BRUTOPESO, BRUTOMODO, BRUTOOPERARIO, BRUTOFECHA, TARAPESO, TARAMODO, TARAOPERARIO, TARAFECHA, CHASIS, ACOPLADO, CHOFER, IMPORTE, PENDIENTE, OBSERVACIONES)
VALUES (1, 1, 1, 1, 1, NOW(), 'Origen1', 'Destino1', 50000, 'A', 1, NOW(), 10000, 'A', 1, NOW(), 'XX NNN XX', 'XX NNN XX', 'Chofer1', 0, 0, '');

-- Aqui muestra el ultimo registro insertado 
SELECT * FROM TICKETS
ORDER BY IDTICKET DESC
LIMIT 1;

-- ACTUALIZAR EL ULTIMO TICKET Y REVISAR ESA ACTUALIZACION
UPDATE TICKETS
JOIN (SELECT IDTICKET FROM TICKETS ORDER BY IDTICKET DESC LIMIT 1) AS AUXILIAR
ON TICKETS.IDTICKET = AUXILIAR.IDTICKET
SET TICKETS.BRUTOPESO = 45000, TICKETS.TARAPESO = 15000;


SELECT * FROM TICKETS
ORDER BY IDTICKET DESC
LIMIT 1

-- TAMBIEN SE PUEDE ACTUALIZAR UN TICKET CUALQUIERA 
UPDATE TICKETS
SET BRUTOPESO = 55000, TARAPESO = 12000
WHERE IDTICKET = --Aqui iria el nombre del registro;
