version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.38
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./sql_project:/sql_project
      - ./backup:/backup
    ports:
      - "3306:3306"