USE BALANZA;

-- IMPORTANTE PARA QUE ENTIENDA QUE DEBE HACER LA IMPORTACION
SET GLOBAL local_infile = 1;

-- Tipo de Pructos 8 registros
-- INGRESAR DATOS POR MEDIO DE COMANDO INSERT INTO
INSERT INTO TIPRODUCTO (TIPO, COLOR, ICONO) VALUES
('CEREALES', 'FFC300', '/img/tproductos/cereales.png'),
('OLEAGINOSAS', '1C5C0B', '/img/tproductos/oleaginosas.png'),
('GANADO','7B5104','/img/tproductos/ganado.png'),
('AGROPRUDUCTOS', 'B6F50A', '/img/tproductos/agroproductos.png'),
('BASURA','C80ACB','/img/tproductos/basura.png'),
('METALES','8C9EA6','/img/tproductos/metales.png'),
('ALIMENTOS','FF5733','/img/tproductos/alimentos.png'),
('ARIDOS','16C6F2','/img/tproductos/caridos.png');


-- EMPRESA
-- INGRESAR DATOS POR MEDIO DE COMANDO INSERT INTO
INSERT INTO EMPRESA (RSOCIAL, DOMICILIO, LOCALIDAD,TELEFONO,CORREO) VALUES
('OSCAR CHIANTORE SRL', 'RUTA 17 KM. 176', 'LA PARA','+549 35 75400209','balanza@oscarchiantore.com.ar');

-- TURNOS 3 registros
-- INGRESAR DATOS POR MEDIO DE COMANDO INSERT INTO
INSERT INTO TURNOS (NOMBRE, COLOR, ICONO) VALUES
('MAÑANA', '2CF216', '/img/turnos/manana.png'),
('TARDE', 'F28F16', '/img/turnos/tarde.png'),
('NOCHE', '581845', '/img/turnos/noche.png');

-- Condicion de Clientes 15 registros
-- INGRESAR DATOS POR MEDIO DE COMANDO INSERT INTO
INSERT INTO CONDICION (DESCRIPCION, PRECIO, DPLAZO) VALUES
('CONTADO ESTANDARD', '10000', 0),
('CONTADO BONIFICADO', '7000', 0),
('CONTADO GRANDES CLIENTES', '5000', 0),
('CTA CTE CORTO ESTANDARD', '12000', 15),
('CTA CTE CORTO BONIFICADO', '9000', 15),
('CTA CTE CORTO GRANDES CLIENTES', '6000', 15),
('CTA CTE MEDIO ESTANDARD', '15000', 20),
('CTA CTE MEDIO BONIFICADO', '11000', 20),
('CTA CTE MEDIO GRANDES CLIENTES', '7000', 20),
('CTA CTE LARGO ESTANDARD', '17000', 30),
('CTA CTE LARGO BONIFICADO', '13000', 30),
('CTA CTE LARGO GRANDES CLIENTES', '8000', 30),
('ARENERAS', '7000', 0),
('ENTIDADES PUBLICAS', '10000', 30),
('CTA CTE BONIFICADA GENERAL', '10000', 30);


LOAD DATA  LOCAL INFILE '/sql_project/data_csv/operarios.csv'
INTO TABLE OPERARIO
FIELDS TERMINATED BY ','  ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
-- COLUMNAS QUE ME INTERESA INGESTAR
(NOMBRE,TELEFONO,CORREO,IDEMPRESA);

LOAD DATA  LOCAL INFILE '/sql_project/data_csv/clientes.csv'
INTO TABLE CLIENTES
FIELDS TERMINATED BY ','  ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
-- COLUMNAS QUE ME INTERESA INGESTAR
(IDCONDICION,NOMBRE,TELEFONO,CORREO,ENVIAWA);

LOAD DATA  LOCAL INFILE '/sql_project/data_csv/productos.csv'
INTO TABLE CONDICION
FIELDS TERMINATED BY ','  ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
-- COLUMNAS QUE ME INTERESA INGESTAR
(NOMBRE,IDTIPOPRODUCTO,ICONO);

LOAD DATA  LOCAL INFILE '/sql_project/data_csv/tickete.csv'
INTO TABLE TICKETS
FIELDS TERMINATED BY ','  ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
-- COLUMNAS QUE ME INTERESA INGESTAR
(IDOPERARIO, IDTURNO, IDCLIENTE, IDEMPRESA, IDPRODUCTO, FECHA, ORIGEN, 
DESTINO, BRUTOPESO, BRUTOMODO, BRUTOOPERARIO, BRUTOFECHA, TARAPESO, 
TARAMODO, TARAOPERARIO, TARAFECHA, NETO, CHASIS, ACOPLADO, CHOFER, 
IMPORTE, PENDIENTE, OBSERVACIONES);