USE BALANZA;

DROP PROCEDURE IF EXISTS CREA_OPERARIO;
DROP PROCEDURE IF EXISTS ELIMINAR_OPERARIO;
DROP PROCEDURE IF EXISTS CREA_PRODUCTO;



DELIMITER //

CREATE PROCEDURE CREA_OPERARIO(
    IN O_NOMBRE VARCHAR(100),
    IN O_TELEFONO VARCHAR(20),
    IN O_CORREO VARCHAR(100),
    IN O_IDEMPRESA INT
)
BEGIN
    DECLARE EMPRESA INT;
    
    -- Verificar si existe la Empresa.
    SELECT COUNT(*) INTO EMPRESA
    FROM EMPRESA
    WHERE IDEMPRESA = O_IDEMPRESA;
    
    IF EMPRESA > 0 THEN
        INSERT INTO OPERARIO (NOMBRE, TELEFONO, CORREO, IDEMPRESA)
        VALUES (O_NOMBRE, O_TELEFONO, O_CORREO, O_IDEMPRESA);
        
        SELECT 'Operario ingresado exitosamente';
    ELSE
        SELECT 'No pudimos vincular el operario a la empresa especifidada por que no existe';
    END IF;
END //

DELIMITER ;

DELIMITER //
CREATE PROCEDURE CREA_PRODUCTO(
    IN P_NOMBRE VARCHAR(100),
    IN P_IDTIPOPRODUCTO INT,
    IN P_ICONO VARCHAR(100)
)
BEGIN
    DECLARE TIPOPRODUCTO INT;

    SELECT COUNT(*) INTO TIPOPRODUCTO
    FROM TIPRODUCTO
    WHERE IDTIPOPRODUCTO = P_IDTIPOPRODUCTO;
    
    IF TIPOPRODUCTO > 0 THEN
        INSERT INTO PRODUCTOS (NOMBRE, IDTIPOPRODUCTO, ICONO)
        VALUES (P_NOMBRE, P_IDTIPOPRODUCTO, P_ICONO);
        
        SELECT 'Producto ingresado exitosamente';
    ELSE
        SELECT 'No pudimos crear el producto porque el tipo al que hace referencia no existe';
    END IF;
END //

DELIMITER ;

DELIMITER //

CREATE PROCEDURE ELIMINAR_OPERARIO(IN p_idOperario INT)
BEGIN
    DECLARE operario_existe INT DEFAULT 0;
    DECLARE operario_nombre VARCHAR(100);

    START TRANSACTION;

    SET SQL_SAFE_UPDATES = 0;

    SELECT COUNT(*) INTO operario_existe
    FROM OPERARIO
    WHERE IDOPERARIO = p_idOperario;

    IF operario_existe = 0 THEN
        ROLLBACK;
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El operario no existe';
    ELSE
        SELECT NOMBRE INTO operario_nombre
        FROM OPERARIO
        WHERE IDOPERARIO = p_idOperario;

        INSERT INTO TICKETS_USUARIOS_ELIMINADOS (IDTICKET, IDOPERARIO, NOMBRE_OPERARIO)
        SELECT IDTICKET, IDOPERARIO, operario_nombre
        FROM TICKETS
        WHERE IDOPERARIO = p_idOperario;

        UPDATE TICKETS
        SET IDOPERARIO = 0
        WHERE IDOPERARIO = p_idOperario;

        DELETE FROM OPERARIO
        WHERE IDOPERARIO = p_idOperario;

        COMMIT;
    END IF;
    SET SQL_SAFE_UPDATES = 1;

END //

DELIMITER ;