USE BALANZA;

DROP VIEW IF EXISTS CANTIDAD_TICKETS_POR_TURNOS;
DROP VIEW IF EXISTS TICKETS_POR_TURNOS;
DROP VIEW IF EXISTS TIPODEPRODUCTOS_PRODUCTOS;

-- CANTIDAD DE TICKETS POR FECHA Y TURNO
-- ESTA VISTA ME LISTA LA CANTIDAD DE TICKETS REALIZADAS EN LOS DISTINTIOS TURNOS DE LA UNA FECHA DETERMINADA O DE LA TOTALIDAD DE LAS TABLA 
CREATE VIEW CANTIDAD_TICKETS_POR_TURNOS AS 
SELECT 
	TI.FECHA
, 	TU.NOMBRE
, 	COUNT(TI.IDTICKET) 
FROM 
	TICKETS AS TI 
JOIN TURNOS AS TU 
ON TU.IDTURNO=TI.IDTURNO 
GROUP BY TI.FECHA,TU.IDTURNO;


-- TICKETS POR TURNOS
-- AQUI VOY A TENER UN LISTADO DETALLADO DE LOS TICKETS QUE SE HICIERON EL EL TURNO Y A QUIENES SE LE HICIERON 

CREATE VIEW TICKETS_POR_TURNOS AS 
SELECT 
	TU.NOMBRE AS TURNO
,	TI.FECHA AS FECHA
,   TI.IDTICKET AS NTICKET
, 	CL.NOMBRE AS CLIENTE
FROM 
	TICKETS AS TI 
LEFT JOIN TURNOS AS TU 
ON TU.IDTURNO=TI.IDTURNO
LEFT JOIN CLIENTES AS CL
ON CL.IDCLIENTE=TI.IDCLIENTE
ORDER BY TU.IDTURNO;

-- PRODUCTOS POR TIPO
-- MUESTRA LOS TIPOS DE PRODUCTOS CON SUS RESPECIVOS PRODUCTOS 

CREATE VIEW TIPODEPRODUCTOS_PRODUCTOS AS
SELECT 
	T.IDTIPOPRODUCTO
, 	T.TIPO
,	P.IDPRODUCTO
,	P.NOMBRE
FROM 
	PRODUCTOS P 
LEFT JOIN 
	TIPRODUCTO T 
ON 
	P.IDTIPOPRODUCTO=T.IDTIPOPRODUCTO 
ORDER BY 
	T.TIPO;



