USE BALANZA;

DROP VIEW IF EXISTS CANTIDAD_TICKETS_POR_TURNOS;
DROP VIEW IF EXISTS TICKETS_POR_TURNOS;
DROP VIEW IF EXISTS TIPODEPRODUCTOS_PRODUCTOS;
DROP VIEW IF EXISTS OPERARIOS_EMPRESAS;
DROP VIEW IF EXISTS CLIENTES_CONDICIONES;
DROP VIEW IF EXISTS TICKETS_PENDIENTES;

-- CANTIDAD DE TICKETS POR FECHA Y TURNO
-- ESTA VISTA ME LISTA LA CANTIDAD DE TICKETS REALIZADAS EN LOS DISTINTIOS TURNOS DE LA UNA FECHA DETERMINADA O DE LA TOTALIDAD DE LAS TABLA 
CREATE VIEW CANTIDAD_TICKETS_POR_TURNOS AS 
SELECT 
	TI.FECHA
, 	TU.NOMBRE
, 	COUNT(TI.IDTICKET) 
FROM 
	TICKETS AS TI 
JOIN TURNOS AS TU 
ON TU.IDTURNO=TI.IDTURNO 
GROUP BY TI.FECHA,TU.IDTURNO;


-- TICKETS POR TURNOS
-- AQUI VOY A TENER UN LISTADO DETALLADO DE LOS TICKETS QUE SE HICIERON EL EL TURNO Y A QUIENES SE LE HICIERON 

CREATE VIEW TICKETS_POR_TURNOS AS 
SELECT 
	TU.NOMBRE AS TURNO
,	TI.FECHA AS FECHA
,   TI.IDTICKET AS NTICKET
, 	CL.NOMBRE AS CLIENTE
FROM 
	TICKETS AS TI 
LEFT JOIN TURNOS AS TU 
ON TU.IDTURNO=TI.IDTURNO
LEFT JOIN CLIENTES AS CL
ON CL.IDCLIENTE=TI.IDCLIENTE
ORDER BY TU.IDTURNO;

-- PRODUCTOS POR TIPO
-- MUESTRA LOS TIPOS DE PRODUCTOS CON SUS RESPECIVOS PRODUCTOS 

CREATE VIEW TIPODEPRODUCTOS_PRODUCTOS AS
SELECT 
	T.IDTIPOPRODUCTO
, 	T.TIPO
,	P.IDPRODUCTO
,	P.NOMBRE
FROM 
	PRODUCTOS P 
LEFT JOIN 
	TIPRODUCTO T 
ON 
	P.IDTIPOPRODUCTO=T.IDTIPOPRODUCTO 
ORDER BY 
	T.TIPO;

-- Operarios por empresa
-- MUESTRA LOS OPERRIOS POR EMPRESA 

CREATE VIEW OPERARIOS_EMPRESAS AS
SELECT
    o.IDOPERARIO,
    o.NOMBRE AS OPERARIO,
    o.TELEFONO,
    o.CORREO,
    e.RSOCIAL AS EMPRESA
FROM OPERARIO o
JOIN EMPRESA e ON o.IDEMPRESA = e.IDEMPRESA;


-- CLIENTES Y CONDICIONES 
-- MUESTRA LOS CLIENTES Y SU CONDICION	

CREATE VIEW CLIENTES_CONDICIONES AS
SELECT
    c.IDCLIENTE,
    c.NOMBRE AS CLIENTE,
    c.TELEFONO,
    c.CORREO,
    co.DESCRIPCION AS CONDICION,
    co.PRECIO
FROM CLIENTES c
JOIN CONDICION co ON c.IDCONDICION = co.IDCONDICION;

-- TICKETS PENDIENTES
-- MUESTRA LOS TICKETS PENDIENTES

CREATE VIEW TICKETS_PENDIENTES AS
SELECT
    IDTICKET,
    FECHA,
    CHASIS,
    ACOPLADO,
    CHOFER,
    IMPORTE
FROM TICKETS
WHERE PENDIENTE = 1;
